# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'ReactDrum - App' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactDrum (App)

    # Depending on how your project is organized, your node_modules directory may be
    # somewhere else; tell CocoaPods where you've installed react-native from npm
    pod 'React', :path => '../../node_modules/react-native', :subspecs => [
        'Core',
        'RCTImage',
        'RCTNetwork',
        'RCTText',
        'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
    ]
    pod 'ReactNativeNavigation', :path => '../../node_modules/react-native-navigation'

end
